# -*- coding: utf-8 -*-
"""Correlacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16i1kX68TvY3aty3QvNdTxR7KLpETU6t8
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Media").getOrCreate()

spark

"""
Contexto:

Se desea saber la relacion entre el salario y las horas trabajadas de un grupo de desarrolladores


"""

csv_file_path = "/content/DataCorre.csv"
dataDessar = spark.read.csv(csv_file_path, header=True, inferSchema=True)

dataDessar.show()

#Hallando correlacion
correlacion = dataDessar.select(corr(col("HorasTrabajadas"),col("Salario")).alias("correlacion")).collect()[0][0]

print("La corrrrelacion es: ", correlacion)