# -*- coding: utf-8 -*-
"""Mediana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8euS3JFGBGxK-7q3rNtUUuwIKjOFmXe
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Mediana").getOrCreate()

spark

"""
Contexto:

Una empresa desea saber el salario típico de los empreados; sin embargo, en los datos también hay salarios de
empleados con cargos altos y de los dueños de esta empresa.


"""

csv_file_path = "/content/DataMediana.csv"
dataAlumnos = spark.read.csv(csv_file_path, header=True, inferSchema=True)

dataAlumnos.show()

#Calculando mediana

"""
Se aplica mediana ya que se tiene valores muy extremos que podrian sesgar el resultado esperado
"""

var_mediana = dataAlumnos.approxQuantile("Salario",[0.5],0.0)
print("La mediana es: ",var_mediana)