# -*- coding: utf-8 -*-
"""Media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16i1kX68TvY3aty3QvNdTxR7KLpETU6t8
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Media").getOrCreate()

spark

"""
Contexto:

En un colegio se tienen las notas de un salon y se desea saber
el promedio de las notas aprobadas y el de las desaprobadas


"""

csv_file_path = "/content/DataMedia.csv"
dataAlumnos = spark.read.csv(csv_file_path, header=True, inferSchema=True)

dataAlumnos.show()

data_Aprobados = dataAlumnos.select(["Nombres", "Edad" , "Nota"]).where(col("Nota") >= 12)
data_Desprobados = dataAlumnos.select(["Nombres", "Edad" , "Nota"]).where(col("Nota") < 12)

#Calculando media / imprimiendo resultados

media_aprobados = data_Aprobados.select(mean(col("Nota")).alias("Promedio aprobados"))
media_aprobados.show()
print("El promedio de notas aprobadas es: ", media_aprobados.collect()[0][0])

media_desaprobados = data_Desprobados.select(mean(col("Nota")).alias("Promedio desaprobados"))
media_desaprobados.show()
print("El promedio de notas aprobadas es: ", media_desaprobados.collect()[0][0])