# -*- coding: utf-8 -*-
"""Moda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kl_aTw-a5TOlM9YzRH8OMYGWEjBWogNz
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Moda").getOrCreate()

spark

"""
Contexto:

En una encuesta realizada a estudiantes UPN,
sobre si estarían dispuestos a consumir en la cafeteria
se desea saber la respuesta más común


"""

csv_file_path = "/content/DataModa.csv"
dataEncuesta = spark.read.csv(csv_file_path, header=True, inferSchema=True)

dataEncuesta.show()

#Calculando la moda
var_moda= dataEncuesta.groupBy("Frecuencia").count().orderBy(col("count").desc()).first()["Frecuencia"]
print("La moda es: ",var_moda)